{% set name = "dl1_data_handler" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e2cbf496d2b5b1ce6b692b3cfeb7993a75d22dd34ad87d7fc09dd5df94646dc  # SHA256 from PyPI

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=65
    - setuptools_scm >=6.2
  run:
    - python >=3.10
    - ctapipe >=0.22,<0.25
    - astropy
    - numpy
    - pandas
    - pip
    - pyyaml
    - scipy
    - traitlets
    - pydot
    - setuptools

test:
  imports:
    - dl1_data_handler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/dl1-data-handler
  summary: "Utilities for reading and processing CTA R1/DL0/DL1 data in a standardized format."
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcervinoucm
    - Tjark Miener
    - Alexander Cervino
